//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BookSaleFairWeb.Web.BookSaleFair
{

    public partial class Books : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string ftitle;
        [Size(50)]
        public string title
        {
            get { return ftitle; }
            set { SetPropertyValue<string>(nameof(title), ref ftitle, value); }
        }
        string fauthor;
        [Size(10)]
        public string author
        {
            get { return fauthor; }
            set { SetPropertyValue<string>(nameof(author), ref fauthor, value); }
        }
        decimal fprice;
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
        int fcount;
        public int count
        {
            get { return fcount; }
            set { SetPropertyValue<int>(nameof(count), ref fcount, value); }
        }
        string fdescription;
        [Size(50)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>(nameof(description), ref fdescription, value); }
        }
        string ftype;
        [Size(50)]
        public string type
        {
            get { return ftype; }
            set { SetPropertyValue<string>(nameof(type), ref ftype, value); }
        }
        [Association(@"orderListReferencesBooks")]
        public XPCollection<orderList> orderLists { get { return GetCollection<orderList>(nameof(orderLists)); } }
    }

}
