//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BookSaleFairWeb.Web.BookSaleFair
{

    public partial class Orders : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        DateTime fdate;
        public DateTime date
        {
            get { return fdate; }
            set { SetPropertyValue<DateTime>(nameof(date), ref fdate, value); }
        }
        decimal ftotalPrice;
        public decimal totalPrice
        {
            get { return ftotalPrice; }
            set { SetPropertyValue<decimal>(nameof(totalPrice), ref ftotalPrice, value); }
        }
        string fcustomerName;
        [Size(50)]
        public string customerName
        {
            get { return fcustomerName; }
            set { SetPropertyValue<string>(nameof(customerName), ref fcustomerName, value); }
        }
        Employees femployeeID;
        [Association(@"OrdersReferencesEmployees")]
        public Employees employeeID
        {
            get { return femployeeID; }
            set { SetPropertyValue<Employees>(nameof(employeeID), ref femployeeID, value); }
        }
        Customers fcustomerId;
        [Association(@"OrdersReferencesCustomers")]
        public Customers customerId
        {
            get { return fcustomerId; }
            set { SetPropertyValue<Customers>(nameof(customerId), ref fcustomerId, value); }
        }
        [Association(@"orderListReferencesOrders")]
        public XPCollection<orderList> orderLists { get { return GetCollection<orderList>(nameof(orderLists)); } }
    }

}
