//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace BookSaleFairWeb.Web.BookSaleFair
{

    public partial class Users : XPLiteObject
    {
        string ffirstName;
        [Size(50)]
        public string firstName
        {
            get { return ffirstName; }
            set { SetPropertyValue<string>(nameof(firstName), ref ffirstName, value); }
        }
        string flastName;
        [Size(50)]
        public string lastName
        {
            get { return flastName; }
            set { SetPropertyValue<string>(nameof(lastName), ref flastName, value); }
        }
        string ftype;
        [Size(10)]
        public string type
        {
            get { return ftype; }
            set { SetPropertyValue<string>(nameof(type), ref ftype, value); }
        }
        string fuserName;
        [Size(50)]
        public string userName
        {
            get { return fuserName; }
            set { SetPropertyValue<string>(nameof(userName), ref fuserName, value); }
        }
        string fpassword;
        [Size(50)]
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>(nameof(password), ref fpassword, value); }
        }
        string femail;
        [Size(50)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fgender;
        [Size(10)]
        public string gender
        {
            get { return fgender; }
            set { SetPropertyValue<string>(nameof(gender), ref fgender, value); }
        }
        byte[] fimage;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] image
        {
            get { return fimage; }
            set { SetPropertyValue<byte[]>(nameof(image), ref fimage, value); }
        }
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        [Association(@"EmployeesReferencesUsers")]
        public XPCollection<Employees> EmployeesCollection { get { return GetCollection<Employees>(nameof(EmployeesCollection)); } }
    }

}
